#!/bin/sh
#
# Runs the stats script against all optimizers for a given model

GRY='\e[1;30m'
MGT='\e[0;35m'
NRM='\e[0m'

args="$0 $*"
n_args=$(($# + 1))
printf "${GRY}args ${NRM}%s${GRY} [ ${MGT}%s${GRY} ]${NRM}\n" $n_args "$args" >&2

runs=$1
threshold=$2
model=$3
places=$4
order=$5
agents=$6
iterations=$7
lower=$8
upper=$9

if [ $order -ge 8 ]
then
    adaptive="adaptive"
else
    adaptive="non-adaptive"
fi

# Nelder-Mead
./stats $runs $threshold ./nm-$model-std $places fixed $order 1.0e-9 $(((agents - 1) * iterations + agents)) \
    $(printf "scale=3; 0.5 * ($upper - $lower);\n" | /usr/bin/bc) $adaptive random $lower $upper >/dev/null

# Unclamped
./stats $runs $threshold ./cut-$model-std $places fixed $order $agents $iterations unclamped $lower $upper >/dev/null
