#!/bin/sh

MGT='\e[0;35m'
NRM='\e[0m'

model=$1
places=$2
format=$3
dim=$4
lower=$5
upper=$6

size=$(echo "scale=3; ($upper - $lower) / 10.0;" | /usr/bin/bc)

precision='1.0e-6'

if [ $dim -ge 8 ]; then
    adaptive=1
else
    adaptive=0
fi

echo "${MGT}Nelder-Mead${NRM}"
./nm-$model-std $places $format $dim $precision 100000 $size $adaptive 1 $lower $upper >/dev/null
echo ""
sleep 1

echo "${MGT}Multidirectional Search${NRM}"
./mds-$model-std $places $format $dim $precision 100000 $size 1 $lower $upper >/dev/null
echo ""
sleep 1

echo "${MGT}Spiral & Nelder-Mead${NRM}"
set -- $(./spiral-$model-std $places $format $dim 100 200 0 $lower $upper 2>&1 >/dev/null | tail -1)
echo "     $*"
shift 3
while [ $# -gt 2 ]; do
    spiral_args="$spiral_args $1 "
    shift
done
./nm-$model-std $places $format $dim $precision 10000 $(echo "scale=9; ($upper - $lower) / 100000.0;" | /usr/bin/bc) $adaptive 0 $spiral_args >/dev/null
echo ""
sleep 1

echo "${MGT}Whale & Nelder-Mead${NRM}"
set -- $(./whale-$model-std $places $format $dim 100 200 $lower $upper 2>&1 >/dev/null | tail -1)
echo "     $*"
shift 3
while [ $# -gt 2 ]; do
    whale_args="$whale_args $1 "
    shift
done
./nm-$model-std $places $format $dim $precision 10000 $(echo "scale=9; ($upper - $lower) / 100000.0;" | /usr/bin/bc) $adaptive 0 $whale_args >/dev/null
