#!/bin/sh

model=$1
places=$2
format=$3
dim=$4
lower=$5
upper=$6

if [ $dim -ge 8 ]; then
    adaptive=1
else
    adaptive=0
fi

./nm-$model-std $places $format $dim 1.0e-6 10000 $adaptive $lower $upper >/dev/null

./mds-$model-std $places $format $dim 1.0e-6 10000 $lower $upper >/dev/null

./whale-$model-std $places $format $dim 200 500 $lower $upper >/dev/null

./spiral-$model-std $places $format $dim 200 500 $lower $upper >/dev/null
