#!/bin/sh
#
# Runs a specified model against all optimizers

GRY='\e[1;30m'
MGT='\e[0;35m'
NRM='\e[0m'

args="$0 $*"
n_args=$(($# + 1))
echo "${GRY}args ${NRM}${n_args}${GRY} [ ${MGT}${args}${GRY} ]${NRM}" >&2

model=$1
order=$2
agents=$3
iterations=$4
lower=$5
upper=$6

if [ $order -ge 8 ]
then
    adaptive=1
else
    adaptive=0
fi

# Nelder-Mead
./nm-$model-std 3 0 $order 1.0e-6 100000 $(echo "scale=3; 0.5 * ($upper - $lower);" | /usr/bin/bc) \
    $adaptive $((agents * iterations)) $lower $upper >/dev/null

if [ $order -le 8 ]
then
    # Periodic Descent Direction Setting
    ./spiral-$model-std 3 0 $order $agents $iterations 0 $lower $upper >/dev/null

    # Convergence Setting
    ./spiral-$model-std 3 0 $order $agents $iterations 1 $lower $upper >/dev/null
fi

# Un-clamped
./cut-$model-std 3 0 $order $agents $iterations 0 $lower $upper >/dev/null

# Clamped
./cut-$model-std 3 0 $order $agents $iterations 1 $lower $upper >/dev/null

if [ $order -le 8 ]
then
    # Base-line
    ./rnd-$model-std 3 0 $order $(((agents - 1) * iterations)) $lower $upper >/dev/null
fi
