#!/bin/sh
#
# Runs a specified model against all optimizers

GRY='\e[1;30m'
MGT='\e[0;35m'
NRM='\e[0m'

args="$0 $*"
n_args=$(($# + 1))
printf "${GRY}args ${NRM}%s${GRY} [ ${MGT}%s${GRY} ]${NRM}\n" $n_args "$args" >&2

model=$1
places=$2
order=$3
agents=$4
iterations=$5
lower=$6
upper=$7

if [ $order -ge 8 ]
then
    adaptive="adaptive"
else
    adaptive="non-adaptive"
fi

# Nelder-Mead
./nm-$model-std $places fixed $order 1.0e-9 $(((agents - 1) * iterations + agents)) \
    $(printf "scale=3; 0.5 * ($upper - $lower);\n" | /usr/bin/bc) $adaptive bulk $lower $upper >/dev/null

# Cut (unclamped)
./cut-$model-std $places fixed $order $agents $iterations unclamped $lower $upper >/dev/null

# Cut (clamped)
./cut-$model-std $places fixed $order $agents $iterations clamped $lower $upper >/dev/null

# Random
./cut-$model-std $places fixed $order $agents $iterations random $lower $upper >/dev/null
