#!/bin/sh

GRY='\e[1;30m'
RED='\e[0;31m'
GRN='\e[0;32m'
MGT='\e[0;35m'
NRM='\e[0m'

args="$0 $*"
n_args=$(($# + 1))
echo "${GRY}args ${NRM}${n_args}${GRY} [ ${MGT}${args}${GRY} ]${NRM}" >&2

samples=$1
threshold=$2
shift 2
args="$*"

passed=0
failed=0
count=1
while [ $count -le $samples ]
do
    echo -n "${GRY}$count ${NRM}"
    set -- $($args 2>/dev/null | tail -1)
    result=$*
    shift $(($# - 1))
    if [ $(echo "scale=9; $1 > $threshold;" | /usr/bin/bc)  -eq 1 ]
    then
        failed=$((failed + 1))
        colour=${RED}
    else
        passed=$((passed + 1))
        colour=${GRN}
    fi
    echo ${colour}${result}${NRM}
    sleep 1
    count=$((count + 1))
done

echo "${GRY}Passed${NRM} $passed  ${GRY}Failed${NRM} $failed"
